### ISSUE TITLE
FixWhitespace will mess up the indentation of my Coffeescript

### ISSUE THREAD

**Issue by joallard** [bronson/vim-trailing-whitespace#11]
Repro: Just call it on a regular Coffee file

**Comment by bronson** [comment]
I suddenly find myself with a [bunch of coffescript](https://github.com/atom/atom) on my hard drive so I tried to repro this.

I tried it on the six files beginning with `d` in `src`...  Worked fine.  Can you supply a repro?

**Comment by joallard** [comment]
If I take eg. `decoration.coffee`, I get a totally different file. Do you have a special Coffeescript indenter or something? Maybe that's the issue

**Comment by joallard** [comment]
Looks like updating my `vim-coffee-script` did it. Don't know what I was thinking submitting a bug here. Anyway, thanks!
