### ISSUE TITLE
Should we highlight spaces that are preceeded by a backslash?

### ISSUE THREAD

**Issue by hugomg** [bronson/vim-trailing-whitespace#12]
Right now, vim-trailing-whitespace is complaining about the trailing space in the following line in my .vimrc:

    set showbreak=↪\ \ \ 

However, the final space, after the third backslash, is part of the value that I am assigning to showbreak. Perhaps the whitespace-detection regexes should allow whitespace if it is preceded by a backslash?

    /\s\+$/        " Current regex
    /\\\@<!\s\+$/  " Proposed regex

**Comment by bronson** [comment]
That's a good point.  Feel like trying it out and sending a PR if you like it?

**Comment by bronson** [comment]
Fixed by #13, I'm glad you persisted.
