### ISSUE TITLE
trailing-whitespaces is highlighting spaces in leaderguide

### ISSUE THREAD

**Issue by ScrumpyJack** [bronson/vim-trailing-whitespace#22]
Since pulling the latest version into vim, trailing-whitespaces highlights trailing white spaces in leaderguide, which is a bit ugly.

Is there a way I can stop this from happening?

<img width="1219" alt="leaderguide" src="https://user-images.githubusercontent.com/3187469/99287044-a9127600-2831-11eb-9ec0-aa2853605221.png">

**Comment by bronson** [comment]
Yes, this is due https://github.com/bronson/vim-trailing-whitespace/commit/b5289251ae8f93473febdcf2fd10e39a8287d9fd. And it will affect more than just leaderguide...  Reverting.

@ZwodahS do you have an idea for a DefX fix that doesn't affect buffers like these?

**Comment by bronson** [comment]
Thanks for pointing this out.

**Comment by ZwodahS** [comment]
How I solve this for defx is to include it in the ignored list
let g:extra_whitespace_ignored_filetypes = ['defx']

I think previously, the plugin wasn't triggered for these filetypes, hence they are showing up now.

**Comment by ZwodahS** [comment]
@bronson not sure if you are intending to merge my commit in, but I also added BufEnter, as <C-O> also reset the highlight Defx. I will maintain my own fork for now =)

https://github.com/ZwodahS/vim-trailing-whitespace/commit/87929b3b5fbe974ffa4260d1dfc357b3053411d2
